(function(b,c){typeof define==="function"&&define.amd?define("index/db.index",["db"],c):b.DB=c(b.DB)})(this,function(b){b.extend({get_linking_url_list:b.httpMethod({url:"/cgi-bin/get_linking_url_list"}),get_bottom_agency:b.httpMethod({url:"/cgi-bin/tool/get_bottom_agency"}),getTypeData:b.httpMethod({url:"/cgi-bin/index_type"})});return b});
define("template/index/agency_list",[],function(){return function(b){b=b||{};with(b){for(var b=[],c=0;c<items.length;c++)b.push('<li class="mod-agency-list__agency"><a target="_blank" href="http://',items[c].agency_domain,'" class="mod-agency-list__link-agency" title="',items[c].agency_name,'" report-tdw="action=organization_pic&ver3=',c+1,'"><img lazy-src="',items[c].agency_url,'" class="mod-agency-list__img" /></a></li>');return b.join("")}}});
define("template/index/category_3",[],function(){return function(b){b=b||{};with(b){b=[];b.push('<div class="',isGrayBg?"wrap-bg-gray":"",'" jump-end="true"> <div class="wrap-catalog-box">  <div class="mod-catalog-box mod-catalog-box_h" data-fid="',f_id,'" data-type="',type,'" data-index="',floorIndex,'"> <div class="mod-catalog-box__header" jump-through="',floorIndex,'"> <a href="http://ke.qq.com/cgi-bin/courseList?mt=',f_id,'" class="mod-catalog-box__title" target="_blank" jump-start="topfloor_title_click">',
f_name,'</a> <ul class="mod-catalog-box__nav"> ');for(var c=0,e=s_items.length;c<e;c++){var a=s_items[c];b.push(' <li class="mod-catalog-box__nav-item',a.selected?" mod-catalog-box__nav-item_current":"",'" data-sid="',a.s_id,'" data-index="',c+1,'" jump-through="',c+1,'"><a href="http://ke.qq.com/cgi-bin/courseList?mt=',f_id,"",a.s_id>1E5?"&sort=3":a.s_id===f_id?"":"&st="+a.s_id,'" class="mod-catalog-box__link-nav" target="_blank">',a.s_name,"</a></li> ")}b.push(' </ul>  </div> <div class="mod-catalog-box__content clearfix"> <a href="',
cover_action_url,'" class="mod-catalog-box__link-img" target="_blank" jump-start="topfloor_banner" jump-through="',floorIndex,'"> <img lazy-src="',cover_pic_url,'" alt="',cover_tips,'" title="',cover_tips,'" class="mod-catalog-box__img" width="465" height="220"/> </a> <div class="mod-catalog-box__content-bd" data-index="',floorIndex,'"></div> </div> </div>  </div></div>');return b.join("")}}});
define("template/index/category_3_content",[],function(){return function(b){b=b||{};with(b){var c=[];c.push('<ul class="mod-course-card_list"> ');for(var b=0,e=Math.min(items.length,3);b<e;b++){var a=items[b];c.push(' <li class="mod-course-card__item"> <div class="mod-course-card',a.type===2?" mod-course-card_lu":"",'" jump-start="topfloor_class_click" jump-through="',fIndex,"&",sIndex,"&",b+1,'"> <a href="',(a.type===2?"/video/index.html":"/cgi-bin/courseDetail")+"?course_id="+a.course_id,'" target="_blank" class="mod-course-card__link-img" data-id="',
a.course_id,'" data-index="',b+1,'"> <img lazy-src="',a.cover_url,'220" alt="',a.name,'" title="',a.name,'" class="mod-course-card__img" width="220" height="124"/> ');a.type===2&&c.push(' <i class="icon-card-lu"></i> ');c.push(" ");a.expr_flag&&a.expr_flag!==0&&c.push(' <div class="mod-support-listen">\u514d\u8d39\u8bd5\u542c</div> ');c.push(' </a> <div class="course-title"> ');a.activity_label=a.activity_label||[];a.activity_label.forEach(function(a){c.push(' <a class="icon_label" href="',a.activity_url,
'" target="_blank" title="',a.name,'"><img src="',a.icon_url,'" width="12px" height="12px" /></a> ')});c.push(' <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-card__name" title="',a.name,'" data-id="',a.course_id,'" data-index="',b+1,'">',a.name,'</a> </div> <p class="mod-course-card__line"> <span class="mod-course-card__price',a.price===0?" mod-course-card__price_free":"",'">',$.render.formatPrice(a.price),'</span> <i class="icon-sep"></i> ');a.famousV?
c.push(' <span class="mod-course-card__teacher">',a.famousName,'<a class="v-flag" report-tdw="module=V-VJT&action=v-clk&ver1=item.course_id" title="\u540d\u4eba\u8bb2\u5e08" href="http://ke.qq.com/activity/lectureroom/index.html?from=10" target="_blank"></a></span> '):c.push(' <a href="http://',a.agency_domain,'" target="_blank" class="mod-course-card__agency" title="',a.agency_name,'" report-tdw="action=topfloor_organization&ver1=',a.course_id,'">',a.agency_name,"</a> ");c.push(" </p> </div> </li> ")}c.push("</ul>");
return c.join("")}}});
define("template/index/category_6",[],function(){return function(b){b=b||{};with(b){b=[];b.push('<div class="',isGrayBg?"wrap-bg-gray":"",'" jump-end="true"> <div class="wrap-catalog-box">  <div class="mod-catalog-box mod-catalog-box_v" data-fid="',f_id,'" data-type="',type,'" data-index="',floorIndex,'"> <div class="mod-catalog-box__header" jump-through="',floorIndex,'"> <a href="http://ke.qq.com/cgi-bin/courseList?mt=',f_id,'" class="mod-catalog-box__title" target="_blank" jump-start="topfloor_title_click">',f_name,
'</a> <ul class="mod-catalog-box__nav"> ');for(var c=0,e=s_items.length;c<e;c++){var a=s_items[c];b.push(' <li class="mod-catalog-box__nav-item',a.selected?" mod-catalog-box__nav-item_current":"",'" data-sid="',a.s_id,'" data-index="',c+1,'" jump-through="',c+1,'"><a href="http://ke.qq.com/cgi-bin/courseList?mt=',f_id,"",a.s_id>1E5?"&sort=3":a.s_id===f_id?"":"&st="+a.s_id,'" class="mod-catalog-box__link-nav" target="_blank" jump-start="topfloor_tab_click">',a.s_name,"</a></li> ")}b.push(' </ul>  </div> <div class="mod-catalog-box__content clearfix"> <a href="',
cover_action_url,'" target="_blank" class="mod-catalog-box__link-img" jump-start="topfloor_banner" jump-through="',floorIndex,'"> <img lazy-src="',cover_pic_url,'" alt="',cover_tips,'" title="',cover_tips,'" class="mod-catalog-box__img mod-catalog-box-banner" width="240" height="420"/> </a> <div class="mod-catalog-box__content-bd" data-index="',floorIndex,'"></div> </div> </div>  </div></div>');return b.join("")}}});
define("template/index/category_6_content",[],function(){return function(b){b=b||{};with(b){var c=[];c.push('<ul class="mod-course-card_list"> ');for(var b=0,e=Math.min(items.length,6);b<e;b++){var a=items[b];c.push(' <li class="mod-course-card__item"> <div class="mod-course-card',a.type===2?" mod-course-card_lu":"",'" jump-start="topfloor_class_click" jump-through="',fIndex,"&",sIndex,"&",b+1,'"> <a href="',(a.type===2?"/video/index.html":"/cgi-bin/courseDetail")+"?course_id="+a.course_id,'" target="_blank" class="mod-course-card__link-img" data-id="',
a.course_id,'" data-index="',b+1,'"> <img lazy-src="',a.cover_url,'220" alt="',a.name,'" title="',a.name,'" class="mod-course-card__img" width="220" height="124"/> ');a.type===2&&c.push(' <i class="icon-card-lu"></i> ');c.push(" ");a.expr_flag&&a.expr_flag!==0&&c.push(' <div class="mod-support-listen">\u514d\u8d39\u8bd5\u542c</div> ');c.push(' </a> <div class="course-title"> ');a.activity_label=a.activity_label||[];a.activity_label.forEach(function(a){c.push(' <a class="icon_label" href="',a.activity_url,
'" target="_blank" title="',a.name,'"><img src="',a.icon_url,'" width="12px" height="12px" /></a> ')});c.push(' <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-card__name" title="',a.name,'" data-id="',a.course_id,'" data-index="',b+1,'">',a.name,'</a> </div> <p class="mod-course-card__line"> <span class="mod-course-card__price',a.price===0?" mod-course-card__price_free":"",'">',$.render.formatPrice(a.price),'</span> <i class="icon-sep"></i> ');a.famousV?
c.push(' <span class="mod-course-card__teacher">',a.famousName,'<a class="v-flag" report-tdw="module=V-VJT&action=v-clk&ver1=item.course_id" title="\u540d\u4eba\u8bb2\u5e08" href="http://ke.qq.com/activity/lectureroom/index.html?from=10" target="_blank"></a></span> '):c.push(' <a href="http://',a.agency_domain,'" target="_blank" class="mod-course-card__agency" title="',a.agency_name,'" report-tdw="action=topfloor_organization&ver1=',a.course_id,'" >',a.agency_name,"</a> ");c.push(" </p> </div> </li> ")}c.push('</ul><div class="mod-catalog-box__wrap-course-rank" jump-end="true">  <div class="mod-course-rank" jump-through="',
fIndex,'"> <div class="mod-course-rank__header"> <ul class="mod-course-rank__nav"> <li class="mod-course-rank__nav-item',showRankTab==="free"?" mod-course-rank__nav-item_current":"",'" data-sid="',s_id,'" data-tab="free"><a class="mod-course-rank__link-nav">\u514d\u8d39\u6392\u884c</a></li> <li class="mod-course-rank__nav-item',showRankTab!=="free"?" mod-course-rank__nav-item_current":"",'" data-sid="',s_id,'" data-tab="pay"><a class="mod-course-rank__link-nav">\u4ed8\u8d39\u6392\u884c</a></li> </ul> </div> <div class="mod-course-rank__content"> <ul class="mod-course-rank__rank-list',
showRankTab==="free"?" mod-course-rank__rank-list_current":"",'" data-tab="free" jump-through="1"> ');b=0;for(e=Math.min(free_course_list.length,9);b<e;b++)a=free_course_list[b],c.push(' <li class="mod-course-rank__rank-item',b===0?" mod-course-rank__rank-item_first":"",'" jump-start="topfloor_rank_click" jump-through="',b+1,'"> <span class="mod-course-rank__rank-number mod-course-rank__rank-number_',b+1,'">',b+1,"</span> "),b===0?c.push(' <div class="mod-course-rank__rank-content"> <a href="/cgi-bin/courseDetail?course_id=',
a.course_id,'" target="_blank" class="mod-course-rank__course-name" title="',a.name,'" data-id="',a.course_id,'">',a.name,'</a> <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-rank__link-img" data-id="',a.course_id,'"> <img lazy-src="',a.cover_url,'90" alt="',a.name,'" title="',a.name,'" class="mod-course-rank__course-img" width="90" height="50"/> </a> <div class="mod-course-rank__course-des"> <span class="mod-course-rank__course-price">',a.apply_num+"\u4eba",
'</span> <span class="mod-course-rank__agency-name" title="',a.agency_name,'">',a.agency_name,"</span> </div> </div> "):c.push(' <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-rank__course-name" title="',a.name,'" data-id="',a.course_id,'">',a.name,"</a> "),c.push(" </li> ");c.push(' </ul> <ul class="mod-course-rank__rank-list',showRankTab!=="free"?" mod-course-rank__rank-list_current":"",'" data-tab="pay" jump-through="2"> ');b=0;for(e=Math.min(pay_course_list.length,
9);b<e;b++)a=pay_course_list[b],c.push(' <li class="mod-course-rank__rank-item',b===0?" mod-course-rank__rank-item_first":"",'" jump-start="topfloor_rank_click" jump-through="',b+1,'"> <span class="mod-course-rank__rank-number mod-course-rank__rank-number_',b+1,'">',b+1,"</span> "),b===0?c.push(' <div class="mod-course-rank__rank-content"> <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-rank__course-name" title="',a.name,'" data-id="',a.course_id,'">',a.name,
'</a> <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-rank__link-img" data-id="',a.course_id,'"> <img lazy-src="',a.cover_url,'90" alt="',a.name,'" title="',a.name,'" class="mod-course-rank__course-img" width="90" height="50"/> </a> <div class="mod-course-rank__course-des"> <span class="mod-course-rank__course-price">',$.render.formatPrice(a.price),'</span> <span class="mod-course-rank__agency-name" title="',a.agency_name,'">',a.agency_name,"</span> </div> </div> "):
c.push(' <a href="/cgi-bin/courseDetail?course_id=',a.course_id,'" target="_blank" class="mod-course-rank__course-name" title="',a.name,'" data-id="',a.course_id,'">',a.name,"</a> "),c.push(" </li> ");c.push(" </ul> </div> </div> </div>");return c.join("")}}});
define("template/index/nodata",[],function(){return function(b){b=b||{};with(b)return b=[],b.push('<div class="nodata"><div class="nodata-content"><span class="nodata-log"></span>\u6570\u636e\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7<a href="javascript:void(0)" class="nor-link nodata-retry" data-sid="',sid,'">\u70b9\u51fb\u91cd\u8bd5</a></div></div>'),b.join("")}});
define("template/index","./index/agency_list,./index/category_3,./index/category_3_content,./index/category_6,./index/category_6_content,./index/nodata".split(","),function(b,c,e,a,n,i){return{agency_list:b,category_3:c,category_3_content:e,category_6:a,category_6_content:n,nodata:i}});
(function(b,c){typeof define==="function"&&define.amd?define("index/pageViewer",["jquery"],c):b.PageViewer=c(b.jQuery)})(this,function(b){var c=function(b){this.pre_btn=b.pre_btn;this.next_btn=b.next_btn;this.container=b.container;this.width=b.width;this.isShow=!!b.isShow;this.maxPage=b.maxPage;this.action=b.action;this.curPage=this.curMaxPage=1;this.init()};c.prototype={init:function(){this.lazyLoad()},bindCoursePage:function(){if(this.maxPage<=1)return false;var b=this.container.parent().parent(),
a=this;if(this.isShow)a.pre_btn.show(),a.next_btn.show();else b.on("mouseenter",function(){a.pre_btn.show();a.next_btn.show()}).on("mouseleave",function(){a.pre_btn.hide();a.next_btn.hide()});this.pre_btn.on("click",function(){a.curPage<=1||(a.curPage-=1,a.container.animate({marginLeft:"+="+a.width+"px"},"normal"),a.checkBtnStatus())});this.next_btn.on("click",function(b){if(!(a.curPage>=a.maxPage)){a.curPage+=1;a.container.animate({marginLeft:"-="+a.width+"px"},"normal");a.lazyLoad();a.checkBtnStatus();
if(a.curPage>a.curMaxPage&&a.curPage<a.maxPage)a.curMaxPage=a.curPage,a.action({page:a.curPage+1,cont:a.container},b);b.preventDefault()}})},lazyLoad:function(){var c=b(this.container.find(".market-list-mod")[this.curPage-1]);c&&!c.attr("data-lazyDone")&&(c.attr("data-lazyDone","1"),c.lazyload())},checkBtnStatus:function(){this.curPage<=1?(this.pre_btn.addClass("pre-btn-dis"),this.next_btn.removeClass("next-btn-dis")):this.curPage>=this.maxPage?(this.pre_btn.removeClass("pre-btn-dis"),this.next_btn.addClass("next-btn-dis")):
(this.pre_btn.removeClass("pre-btn-dis"),this.next_btn.removeClass("next-btn-dis"))}};return c});
(function(b,c){typeof define==="function"&&define.amd?define("index/course.list","jquery,index/db.index,report,header,common/html,template/index".split(","),c):b.CourseList=c(b.jQuery,b.DB,b.report,b.header,b.html)})(this,function(b,c,e,a,n,i){function m(a){for(var a=a.sid,b=0,c=h.length;b<c;b++)for(var f=0,d=h[b].s_items.length;f<d;f++)if(h[b].s_items[f].s_id==a)return h[b].s_items[f];return null}function j(a,r){c.getTypeData({param:{req_list:JSON.stringify(a)},succ:function(a){var a=a.result,c=
+new Date,d;for(d in a){var l=m({sid:parseInt(d)});l?b.extend(true,l,a[d],{timestamp:c,loaded:true}):console.log("record not found!")}r&&r(null)},err:function(a){r&&r(a);return true}})}function s(){p.on("mouseenter",".mod-catalog-box__nav-item",function(){var a=b(this);if(a.hasClass("mod-catalog-box__nav-item_current"))return false;var c=a.data("sid"),f=a.closest(".mod-catalog-box"),d=f.data("type"),f=f.data("fid"),l=m({sid:c}),h=a.closest(".mod-catalog-box").data("index"),u=a.data("index"),n=a.closest(".mod-catalog-box").find(".mod-catalog-box__content-bd");
a.closest(".mod-catalog-box__nav").find(".mod-catalog-box__nav-item").removeClass("mod-catalog-box__nav-item_current");a.addClass("mod-catalog-box__nav-item_current");t[f]=c;l.fIndex=h;l.sIndex=u;l.loaded?(o(n,l,d),+new Date-l.timestamp>3E5&&j([c],function(a){g(c)&&!a&&(l=m({sid:c}),o(n,l,d))})):(n.html(""),d===3?n.spin({top:80,left:350}):n.spin({top:180,left:480}),j([c],function(a){g(c)&&(a?n.html(i.nodata({sid:c})):(n.spin(false),l=m({sid:c}),o(n,l,d)))}));e.tdw({action:"topfloor_tab_hover",obj3:q.role_type,
ver2:h,ver3:u})});p.on("mouseenter",".mod-course-rank__nav-item",function(){var a=b(this);if(a.hasClass("mod-course-rank__nav-item_current"))return false;var c=a.closest(".mod-course-rank").find(".mod-course-rank__rank-list"),f=a.data("sid"),d=a.data("tab"),l=a.closest(".mod-catalog-box").data("index"),f=m({sid:f});a.closest(".mod-course-rank__nav").find(".mod-course-rank__nav-item").removeClass("mod-course-rank__nav-item_current");a.addClass("mod-course-rank__nav-item_current");c.removeClass("mod-course-rank__rank-list_current");
c.filter(function(a,c){if(b(c).data("tab")===d)return true}).addClass("mod-course-rank__rank-list_current");f.showRankTab=d;e.tdw({action:"topfloor_rank_view",obj3:q.role_type,ver2:l,ver3:d==="pay"?1:2})});p.on("click",".nodata-retry",function(){var a=b(this),c=a.closest(".mod-catalog-box__content-bd"),f=a.closest(".mod-catalog-box").data("type"),d=a.data("sid");c.html("");f===3?c.spin({top:80,left:350}):c.spin({top:180,left:480});j([d],function(a){g(d)&&(a?c.html(i.nodata({sid:d})):(c.spin(false),
record=m({sid:d}),o(c,record,f)))})});p.on("click",".mod-catalog-box .mod-catalog-box__title",function(){var a=b(this).closest(".mod-catalog-box").data("index");e.tdw({action:"topfloor_title_click",obj3:q.role_type,ver2:a})});p.on("click",".mod-catalog-box .mod-catalog-box__img",function(){var a=b(this).closest(".mod-catalog-box").data("index");e.tdw({action:"topfloor_banner",obj3:q.role_type,ver2:a})});p.on("click",".mod-catalog-box__nav-item",function(){e.tdw({action:"topfloor_tab_click",obj3:q.role_type})});
p.on("click",".mod-catalog-box .mod-course-card__link-img, .mod-catalog-box .mod-course-card__name",function(){var a=b(this),c=a.data("id"),f=a.data("index"),d=a.closest(".mod-catalog-box").find(".mod-catalog-box__nav-item_current").data("index"),a=a.closest(".mod-catalog-box").data("index");e.tdw({action:"topfloor_class_click",obj1:d,obj3:q.role_type,ver1:c,ver2:a,ver3:f})});p.on("click",".mod-course-rank .mod-course-rank__link-img, .mod-course-rank .mod-course-rank__course-name",function(){var a=
b(this),c=a.data("id"),f=a.closest(".mod-course-rank__rank-list").data("tab"),d=a.closest(".mod-catalog-box").find(".mod-catalog-box__nav-item_current").data("index"),a=a.closest(".mod-catalog-box").data("index");e.tdw({action:"topfloor_rank_click",obj1:d,obj3:q.role_type,ver1:c,ver2:a,ver3:f==="pay"?1:2})});var a={};b(window).scroll(function(){for(var c=b(".mod-catalog-box__content-bd"),k,f=0,d=c.length;f<d;f++)k=b(c[f]),k.isOnScreen()&&!a[f]&&(k=k.closest(".mod-catalog-box").data("index"),e.tdw({action:"topfloor_view",
obj3:q.role_type,ver2:k}),a[f]=true)})}function g(a){for(var b in t)if(a===t[b])return true;return false}function v(){for(var a="",c=0,k=h.length;c<k;c++){var f=h[c].s_items[0],d=h[c].type,l=b("<div></div>");f||(f=[]);h[c].isGrayBg=c%2===0;h[c].floorIndex=c+1;f.selected=true;f.fIndex=c+1;f.sIndex=1;d===3?(l.html(i.category_3(h[c])),f.items&&l.find(".mod-catalog-box__content-bd").html(i.category_3_content(f))):d===6&&(l.html(i.category_6(h[c])),f.items&&l.find(".mod-catalog-box__content-bd").html(i.category_6_content(f)));
a+=l.html()}p.html(a).lazyload()}function o(a,b,c){var f="";a.data("index");c===3?f=i.category_3_content(b):c===6&&(f=i.category_6_content(b));a.html(f).lazyload()}var p=b("#categroy-tpl-box"),t={},q={},h=window.categoryInfos;b.fn.isOnScreen=function(){var a=b(window),c=a.scrollTop(),k=a.scrollLeft(),f;f=k+a.width();var a=c+a.height(),d=this.offset();d.right=d.left+this.outerWidth();d.bottom=d.top+this.outerHeight();return!(f<d.left||k>d.right||a<d.top||c>d.bottom)};return{init:function(){a.getInfo(function(a){q=
a||{}});for(var c=[],g=[],k=0,f=h.length;k<f;k++)for(var d=0,l=h[k].s_items.length;d<l;d++)d===0?(c.push(h[k].s_items[d].s_id),t[h[k].f_id]=h[k].s_items[d].s_id):g.push(h[k].s_items[d].s_id),h[k].s_items[d].showRankTab="free",h[k].s_items[d].free_course_list=null,h[k].s_items[d].pay_course_list=null,h[k].s_items[d].items=null;s();v();j(c,function(a){if(a)for(var a=p.find(".mod-catalog-box__content-bd"),d=0,f=a.length;d<f;d++)b(a[d]).html(i.nodata({sid:c[d]}));else v(),j(g)})}}});
(function(b,c){typeof define==="function"&&define.amd?define("common/timing",["jquery"],c):b.Timing=c()})(this,function(b){function c(c,i){var c=c.split("-"),e=[];b(c).each(function(a,b){e.push("flagid=".replace("id",a+1)+b)});for(var j in i)e.push(j+"="+i[j]);j=new Image;a.push(j);j.src="http://isdspeed.qq.com/cgi-bin/r.cgi?"+e.join("&")}function e(a){if(window.performance){var e=performance.timing,m=e.navigationStart,j={},s=1;b("unloadEventStart,unloadEventEnd,redirectStart,redirectEnd,fetchStart,domainLookupStart,domainLookupEnd,connectStart,connectEnd,requestStart,responseStart,responseEnd,domLoading,domInteractive,domContentLoadedEventStart,domContentLoadedEventEnd,domComplete,loadEventStart,loadEventEnd".split(",")).each(function(a,
b){j[s++]=Math.max(e[b]-m,0)});c(a,j)}}var a=[];return{report:function(a){setTimeout(function(){e(a)},0)}}});
(function(b,c){typeof define==="function"&&define.amd?define("common/resource.timing",["jquery"],c):b.ResourceTiming=c()})(this,function(b){function c(a,c){var a=a.split("-"),e=[];b(a).each(function(a,b){e.push("flagid=".replace("id",a+1)+b)});for(var m in c)e.push(m+"="+c[m]);(new Image).src="http://isdspeed.qq.com/cgi-bin/r.cgi?"+e.join("&")}function e(a,e){if(window.performance&&(performance.getEntriesByName||performance.webkitGetEntriesByName)){var i=performance.getEntriesByName?performance.getEntriesByName(e):
performance.webkitGetEntriesByName(e);if(i&&i.length!=0){var i=i[0],m=1,j=[];b("connectEnd,connectStart,domainLookupEnd,domainLookupStart,duration,fetchStart,redirectEnd,redirectStart,requestStart,responseEnd,responseStart,startTime".split(",")).each(function(a,b){j[m++]=Math.ceil(i[b])});c(a,j)}}}return{report:function(a,b){setTimeout(function(){e(a,b)},0)}}});
require("require,jquery,base,report,header,login,db,index/db.index,template/index,template/common,index/pageViewer,index/course.list,common/timing,common/resource.timing".split(","),function(b){var c;function e(){h.getInfo(function(b){b.is_login?a({obj3:b.role_type}):a({obj3:3});o.tdw({action:"Exposure"})})}function a(a){a=a||{};a.module="index";g.initReport(a)}function n(){v.get_linking_url_list({param:{},succ:function(a){a=g.map(a.result.link_out,function(a,b){var c=a.link_url;!c.match(/^http(s)?/)&&
!c.match(/^\/\//)&&(c="http://"+c);return'<li><a class="link-cooperation" href="'+c+'" target="_blank" report-tdw="action=cooperation_click&ver3='+(b+1)+'">'+a.name+"</a></li>"}).join("");g("#js-cooperation-list").html(a)},err:function(){return true}})}function i(){g(".js-mod-category").on("mouseenter mouseleave",function(a){var b=g(this).find(".js-mod-category-side"),c=g(this).data("index");a.type==="mouseenter"?(b.fadeIn(),o.tdw({action:"title_first_hover",ver3:c})):b.stop().hide()});g("#js-course-list").on("mouseenter",
function(){o.tdw({action:"title_first_hover",ver3:"0"})}).on("click",function(a){a.preventDefault();a=g(this).prop("href");o.tdw({action:"title_first_click",ver3:"0"});window.open(a,"_blank")})}function m(){var a={};g("#js_banner").slider({type:"fade",nb:g("#js_slider_next"),pb:g("#js_slider_pre"),sliderbox:g("#js_sliderbox"),slidernav:g("#js_slidernav"),sliderNum:1,isAuto:true,slideCb:function(b){var c=g("#js-big-banner .js-big-banner-nav").eq(b).data("bg-color");g("#js-wrap-banner-bg").css("background",
c);a[b]||(a[b]=true,c=g("#js_sliderbox > li").eq(b).find("img"),o.tdw({action:"Banner-show",ver2:c.attr("src")+","+c.attr("alt"),ver1:b}))}})}function j(){var a="live",b=g("#js-mod-catelog-box .js-nav-item");b.on("mouseenter",function(){var d=g(this),e=d.data("nav");a!=e&&(b.removeClass("mod-catalog-box__nav-item_current"),d.addClass("mod-catalog-box__nav-item_current"),g("#js-"+a+"-course").stop().hide(),g("#js-"+e+"-course").fadeIn(),a=e,o.tdw({action:"hotclass_hover",obj3:c,ver3:e==="live"?1:2}))});
g("#js-mod-catelog-box-hot").on("click",".mod-course-card__link-img, .mod-course-card__name",function(){var b=g(this),f=b.data("id"),b=b.closest(".mod-course-card__item").data("index");o.tdw({action:"hotclass_click",obj3:c,ver1:f,ver2:b+1,ver3:a==="live"?1:2})});g("#js-mod-catelog-box-hot").on("click",".mod-catalog-box__title",function(){o.tdw({action:"topfloor_title_click",obj3:c,ver2:"0"})})}function s(){function a(c){v.get_bottom_agency({param:{page:c.page||1,count:c.count||b},noNeedLogin:true,
succ:function(e){TRecord.push("agency_delay",T[0]+e.delay);g("body").trigger("render",{n:"getAgencyList"});for(var e=e.result,h=g("#js_agency_list"),i="",j=0,m=Math.ceil(e.items.length/b);j<m;j++){var n=e.items.slice(j*b,(j+1)*b);i+='<ul class="mod-agency-list__agencies">'+p.agency_list({items:n})+"</ul>"}h.width(h.width()+1025);c.first?(h.html(i).lazyload(),(new t({container:h,pre_btn:g("#js_agency_pre"),next_btn:g("#js_agency_next"),width:1025,maxPage:Math.ceil(e.total_num/b),isShow:true,action:a})).bindCoursePage()):
h.append(i).lazyload()},err:function(a){TRecord.push("agency_delay",T[0]+a.delay);g("body").trigger("render",{n:"getAgencyList"});c.first&&(a=g("#js_agency_list"),a.html('<li class="l-error">\u6570\u636e\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7<a href="javascript:void(0)" class="nor-link error">\u70b9\u51fb\u91cd\u8bd5</a></li>'),a.find(".nor-link").one("click",function(){s()}));return true}})}var b=8;a({page:1,count:16,first:true})}var g=b("jquery"),v=b("db"),o=b("report"),p=b("template/index"),t=b("index/pageViewer"),
q=b("index/course.list"),h=b("header"),u=b("common/timing"),r=b("common/resource.timing");c=void 0;(function(){TRecord.push("page_main_start");n();i();m();j();s();q.init();TRecord.push("page_main_end");a();TRecord.report("page_start,page_css_ready,page_main_start,page_main_end,page_render_fp,inline_script_run_time".split(","),{delay:50,isd:{inline_script_run_time:8}});e();window.ActiveXObject&&!window.XMLHttpRequest&&setInterval(function(){g("#js_main_nav").get(0).style.zoom=1},1E3);if(document.readyState===
"complete")u.report("7832-39-43");else g(window).on("load",function(){u.report("7832-39-43")});g.loadScript("http://pingjs.qq.com/ping.js",function(){typeof window.pgvMain=="function"&&window.pgvMain()});var b=g('script[src*="common/base"]').attr("src");b&&r.report("7832-39-50",b)})()});window.INDEX_LOAD_SUCC_FLAG=1;define("index/main",function(){});
